##
## Makefile.rules for  in /home/texane/repo/adm/resume/fr
## 
## Made by fabien le mentec <texane@gmail.com>
## 
## Started on  Fri Sep 18 15:40:14 2009 fabien le mentec
## Last update Tue Feb 15 19:12:01 2011 fabien le mentec
##


.PHONY: all clean

%.dvi: %.tex
	convert $(COMMONDIR)/moi.jpg $(COMMONDIR)/moi.eps
	TEXINPUTS=$(COMMONDIR):.:$(TEXINPUTS) latex -interaction=batchmode $< || true

clean:
	rm -f $(OUTPUTDIR)/*.pdf $(OUTPUTDIR)/*.txt *.bak *.log *.aux *.toc *.dvi $(COMMONDIR)/moi.eps
